### ISSUE TITLE
Section about traefik priorities

### ISSUE THREAD

**Issue by youssef-khe** [Pyango/traefik-ai-cheatsheet#1]
It will be good to add a section that talks about rules priorities.

For example:

### Router Rules priorities

```yaml
http:
  routers:
    my-first-router:
      entryPoints: ["web", "websecure"]
      rule: "Host(`example.com`) && PathPrefix(`/api`)"
      service: my-service
      middlewares: ["auth", "ratelimit@file"]
    my-second-router:
      entrypoints: ["web", "websecure"]
      rule: "Host(`example.com`) && PathPrefix(`/api`) && ClientIP(`127.0.0.1`)"
      vice: my-service
      middlewares: ["auth", "ratelimit@file"]
```

By default rules are sorted in decending order using rules length. The priority is directly equal to the length of the rule, and so the longest length has the highest priority.

In this case all requests with Host(`example.com`) will be routed through `my-second-router`
